In [1]:
from numpy import *
a = arrange

Object `arrange` not found.


In [7]:
a = arange(15).reshape(3,5)

In [9]:
a.shape

(3, 5)

In [10]:
a.ndim

2

In [11]:
a.dtype.name

'int64'

In [15]:
a.size

15

In [16]:
type(a)

numpy.ndarray

In [18]:
b = array([6,7,8])
b

In [22]:
type(b)

numpy.ndarray

In [23]:
a = array([2,3,4])
a

In [26]:
a.dtype

dtype('int64')

In [28]:
b = array([1.2, 3.4, 5.1])

In [30]:
b.dtype

dtype('float64')

In [34]:
b = array(([1.5, 2., 3.], 
           [4., 5., 6.]))
b

In [38]:
c = array([[1,2], [3,4]], dtype=complex)
c

In [40]:
zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [43]:
ones((2,3,4), dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [70]:
empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])