In [5]:
import  numpy as np
from scipy import linalg

In [31]:
A = np.array([
    [1, 3],
    [2, 4],
    [0, 5]
], dtype=np.int16)
B = np.array([
    [1, 0],
    [2, 3]
], dtype=np.int16)
print("A({A.shape[0]}x{A.shape[1]}) x B({B.shape[0]}x{B.shape[1]})\n"
      .format(A=A, B=B), A.dot(B))
print("B x A.T\n", B.dot(A.T))
print("B x B^-1\n", B.dot(linalg.inv(B)))
print("A[2][1]= {0} == {1} = A^T[1][2]".format(A[2][1], A.T[1][2]))

A(3x2) x B(2x2)
 [[ 7  9]
 [10 12]
 [10 15]]
B x A.T
 [[ 1  2  0]
 [11 16 15]]
B x B^-1
 [[ 1.  0.]
 [ 0.  1.]]
A[2][1]= 5 == 5 = A^T[1][2]


In [32]:
# Data
D = np.array([
        [1, 2104], # The '1' placeholds for a constant in the h(x)
        [1, 1416],
        [1, 1534],
        [1, 852]
    ])
# Hypotheses
H = np.array([
        [-40, 0.25], # h(x) = -40 + 0.25x
        [200, 0.1],
        [-150, 0.4]
    ])
# Calculate the predictions of all our hypotheses on the training data
# at once!
D.dot(H.T)

array([[ 486. ,  410.4,  691.6],
       [ 314. ,  341.6,  416.4],
       [ 343.5,  353.4,  463.6],
       [ 173. ,  285.2,  190.8]])

In [42]:
A1 = np.array([
        [4, 3],
        [6, 9]
    ])
B1 = np.array([
        [-2, 9],
        [-5, 2]
    ])
print(A1-B1)

x2 = np.array([[2, 7, 4, 1]])
print(1/2 * x2.T)

u3 = np.array([[2], [1], [8]])
print(u3.T)

u4 = np.array([[4], [-4], [-3]])
v4 = np.array([[4,2,4]]).T
print(u4.T.dot(v4))

[[ 6 -6]
 [11  7]]
[[ 1. ]
 [ 3.5]
 [ 2. ]
 [ 0.5]]
[[2 1 8]]
[[-4]]
