In [111]:
ex2(n) = [exp2(x) for x=0:n-1]

function fibonacci (n)
    if n == 0
        return 0
    end
    if n == 1
        return 1
    end
    return fibonacci(n-1) + fibonacci(n-2)
end

fib(n) = [fibonacci(x) for x=0:n-1]

7-element Array{Any,1}:
 1.0
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0

In [110]:
n = 7
vals = hcat( # Matrix: (index-by-function)
    [fn(n) for fn in [ex2, fib,]]...
)

7x2 Array{Float64,2}:
  1.0  0.0
  2.0  1.0
  4.0  1.0
  8.0  2.0
 16.0  3.0
 32.0  5.0
 64.0  8.0

In [120]:
3^(log2(7))

21.84986222490514

In [199]:
function onlinemax(A, k)
    bestscore = maximum(A[1:k])
    for i in k+1:length(A)
        if A[i] > bestscore
            return i
        end
    end
    return length(A)
end

onlinemax (generic function with 1 method)

In [159]:
"""
Perform a Monte Carlo simulation of how different values of k effect 
how often the best candidate is selected.
"""
n = 20
A = collect(1:n)
trials = 1e5

max = maximum(A)
results = zeros(Int16, n, n)
for k in 1:n
    @printf "Running trials for k=%d\n" k
    for t in 1:trials
        shuffle!(A)
        i = onlinemax(A, k)
        results[k, A[i]] += 1
    end
end

Running trials for k=1
Running trials for k=2
Running trials for k=3
Running trials for k=4
Running trials for k=5
Running trials for k=6
Running trials for k=7
Running trials for k=8
Running trials for k=9
Running trials for k=10
Running trials for k=11
Running trials for k=12
Running trials for k=13
Running trials for k=14
Running trials for k=15
Running trials for k=16
Running trials for k=17
Running trials for k=18
Running trials for k=19
Running trials for k=20


In [211]:
# total = zeros(n)
# for j in 1:n
#     for i in 1:n
#         total[j] += results[i, j]
#     end
# end
# total

# Sum all columns 
sum(results, 1)

20-element Array{Float64,1}:
  55151.0
  55170.0
  55515.0
  55726.0
  56437.0
  56853.0
  57193.0
  57880.0
  58825.0
  60432.0
  62646.0
  64343.0
  67156.0
  71445.0
  77583.0
  87471.0
 104951.0
 140143.0
 227939.0
   2853.0

In [218]:
Pkg.add("Plots")
Pkg.add("PyPlot")
Pkg.add("GR")
Pkg.add("PlotlyJS")

INFO: Nothing to be done
INFO: Nothing to be done
INFO: Nothing to be done


LoadError: PlotlyJS can't be installed because it has no versions that support 0.3.2 of julia
while loading In[218], in expression starting on line 4

In [219]:
using Plots
gr()

LoadError: gr not defined
while loading In[219], in expression starting on line 2

In [216]:
x = convert(
    DataFrame,  # Type to convert to 
    Dict(
[@sprintf "Candidate%d" i for i in 1:n], # Column headers
[results[:,i] for i in 1:size(results,2)] # Split up matrix by columns
    )
)
# plot(x, y=:1, Geom.histogram(bincount=20))

20x20 DataFrame
| Row | Candidate1 | Candidate10 | Candidate11 | Candidate12 | Candidate13 |
|-----|------------|-------------|-------------|-------------|-------------|
| 1   | 250        | 3417        | 3955        | 4447        | 5005        |
| 2   | 538        | 1996        | 2462        | 3052        | 3784        |
| 3   | 781        | 1311        | 1706        | 2148        | 2713        |
| 4   | 1019       | 1287        | 1487        | 1721        | 2069        |
| 5   | 1329       | 1436        | 1441        | 1633        | 1976        |
| 6   | 1600       | 1643        | 1633        | 1715        | 1821        |
| 7   | 1876       | 1739        | 1795        | 1904        | 1999        |
| 8   | 2104       | 2081        | 2092        | 2142        | 2241        |
| 9   | 2372       | 2369        | 2398        | 2350        | 2302        |
| 10  | 2691       | 2632        | 2620        | 2616        | 2695        |
| 11  | 2835       | 2933        | 2958        | 2877        | 2812        |
| 12  | 3111       | 3045        | 3255        | 3190        | 3103        |
| 13  | 3509       | 3402        | 3440        | 3392        | 3517        |
| 14  | 3748       | 3743        | 3789        | 3625        | 3633        |
| 15  | 3989       | 3886        | 4011        | 3962        | 4029        |
| 16  | 4171       | 4262        | 4282        | 4266        | 4313        |
| 17  | 4455       | 4473        | 4431        | 4468        | 4426        |
| 18  | 4738       | 4678        | 4782        | 4766        | 4672        |
| 19  | 5050       | 5076        | 5033        | 5053        | 5127        |
| 20  | 4985       | 5023        | 5076        | 5016        | 4919        |

| Row | Candidate14 | Candidate15 | Candidate16 | Candidate17 | Candidate18 |
|-----|-------------|-------------|-------------|-------------|-------------|
| 1   | 5854        | 6549        | 7606        | 8761        | 10448       |
| 2   | 4713        | 5833        | 7280        | 9142        | 12073       |
| 3   | 3559        | 4826        | 6182        | 8809        | 12211       |
| 4   | 2731        | 3706        | 5283        | 7686        | 11381       |
| 5   | 2315        | 3141        | 4338        | 6559        | 10496       |
| 6   | 2122        | 2747        | 3722        | 5631        | 9379        |
| 7   | 2174        | 2527        | 3275        | 4826        | 8364        |
| 8   | 2237        | 2383        | 3125        | 4330        | 7325        |
| 9   | 2394        | 2516        | 2978        | 3823        | 6401        |
| 10  | 2598        | 2750        | 2879        | 3480        | 5665        |
| 11  | 2896        | 2886        | 3112        | 3501        | 5144        |
| 12  | 3116        | 3126        | 3257        | 3498        | 4744        |
| 13  | 3515        | 3394        | 3374        | 3595        | 4294        |
| 14  | 3675        | 3830        | 3720        | 3755        | 4201        |
| 15  | 3927        | 3968        | 3876        | 4043        | 4277        |
| 16  | 4235        | 4233        | 4154        | 4174        | 4239        |
| 17  | 4457        | 4518        | 4525        | 4528        | 4698        |
| 18  | 4761        | 4733        | 4796        | 4676        | 4734        |
| 19  | 5040        | 4927        | 4998        | 5082        | 5012        |
| 20  | 5126        | 4990        | 4991        | 5052        | 5057        |

| Row | Candidate19 | Candidate2 | Candidate20 | Candidate3 | Candidate4 |
|-----|-------------|------------|-------------|------------|------------|
| 1   | 13087       | 528        | 17607       | 787        | 1061       |
| 2   | 16481       | 529        | 25383       | 579        | 626        |
| 3   | 18181       | 811        | 30442       | 831        | 795        |
| 4   | 18565       | 1047       | -31101      | 1082       | 1006       |
| 5   | 18211       | 1273       | -28774      | 1280       | 1322       |
| 6   | 17223       | 1623       | -27535      